In [1]:
import networkx as nx
import obonet
import torch
import pandas as pd

/tmp/ipykernel_1224800/2362945497.py:4: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
#localization
labels_df = pd.read_csv('GNN/subcellular_location.csv')
labels_df.dropna(inplace=True)
location_mapping = {
    'Cell membrane': 0,
    'Nucleus': 1,
    'Cytoplasm': 2
}
labels_df.rename(columns={'GeneSymbol': 'protein'}, inplace=True)
labels_df['Label'] = labels_df['Subcellular_location'].map(location_mapping)
labels_df

protein Subcellular_location  Label
0      OR7A10        Cell membrane      0
1        ORC5              Nucleus      1
2      ZNF596              Nucleus      1
3        SFI1            Cytoplasm      2
4      SUCNR1        Cell membrane      0
...       ...                  ...    ...
8592     INSR        Cell membrane      0
8593   SLC7A1        Cell membrane      0
8594  SLC44A2        Cell membrane      0
8595    PARM1        Cell membrane      0
8596   OR10C1        Cell membrane      0

[8597 rows x 3 columns]

In [3]:
#DosageSensitivity
labels_df = pd.read_csv('GNN/DosageSensitivity.csv')
labels_df.dropna(inplace=True)
location_mapping = {
    'DosageInsensitive': 0,
    'DosageSensitive': 1
}
labels_df.rename(columns={'GeneSymbol': 'protein'}, inplace=True)
labels_df['Label'] = labels_df['DosageSensitivity'].map(location_mapping)
labels_df

protein  DosageSensitivity  Label
0    ZNF627  DosageInsensitive      0
1      ZEB2    DosageSensitive      1
2     PPARD    DosageSensitive      1
3      TBX6  DosageInsensitive      0
4     MBNL2    DosageSensitive      1
..      ...                ...    ...
482   HNF4A    DosageSensitive      1
483  ZNF391  DosageInsensitive      0
484  ZNF707  DosageInsensitive      0
485   ZFP37  DosageInsensitive      0
486   ZNF90  DosageInsensitive      0

[487 rows x 3 columns]

In [4]:
#BivalentVsLys4
labels_df = pd.read_csv('GNN/BivalentVsLys4.csv')
labels_df.dropna(inplace=True)
location_mapping = {
    'Bivalent': 0,
    'Lys4Only': 1
}
labels_df.rename(columns={'GeneSymbol': 'protein'}, inplace=True)
labels_df['Label'] = labels_df['BivalentVsLys4'].map(location_mapping)
labels_df

protein BivalentVsLys4  Label
0     HSD17B1       Bivalent      0
1      NKX2-8       Bivalent      0
2      NKX6-2       Bivalent      0
3    ATP6V0A1       Lys4Only      1
4        IRX4       Bivalent      0
..        ...            ...    ...
179     ZFPM2       Bivalent      0
180    HOXD13       Bivalent      0
181    NKX2-4       Bivalent      0
182   CNTNAP1       Bivalent      0
183    INSIG1       Lys4Only      1

[184 rows x 3 columns]

In [5]:
#BivalentVsNonMethylated
labels_df = pd.read_csv('GNN/BivalentVsNonMethylated.csv')
labels_df.dropna(inplace=True)
location_mapping = {
    'NonMethylated': 0,
    'Bivalent': 1
}
labels_df.rename(columns={'GeneSymbol': 'protein'}, inplace=True)
labels_df['Label'] = labels_df['BivalentVsNonMethylated'].map(location_mapping)
labels_df

protein BivalentVsNonMethylated  Label
0    KCNMA1           NonMethylated      0
1     IFI35           NonMethylated      0
2    HOXD13                Bivalent      1
3     ZFPM2                Bivalent      1
4      NKG7           NonMethylated      0
..      ...                     ...    ...
142    SOX6                Bivalent      1
143    PAX1                Bivalent      1
144     EN2                Bivalent      1
145    SIX2                Bivalent      1
146   SATB1                Bivalent      1

[147 rows x 3 columns]

In [6]:
#Tf_range
labels_df = pd.read_csv('GNN/Tf_range.csv')
labels_df.dropna(inplace=True)
location_mapping = {
    'Short_range': 0,
    'Long_range': 1
}
labels_df.rename(columns={'GeneSymbol': 'protein'}, inplace=True)
labels_df['Label'] = labels_df['Tf_range'].map(location_mapping)
labels_df

protein     Tf_range  Label
0     PITX1  Short_range      0
1       FOS   Long_range      1
2      EGR1  Short_range      0
3     FOXM1  Short_range      0
4      ESR1  Short_range      0
..      ...          ...    ...
169   TEAD1   Long_range      1
170    MAFB  Short_range      0
171    OTX2  Short_range      0
172  NKX6-1  Short_range      0
173  NKX2-1  Short_range      0

[174 rows x 3 columns]

In [7]:
#TF_target_type
labels_df = pd.read_csv('GNN/TF_target_type.csv')
labels_df.dropna(inplace=True)
labels_df = labels_df.iloc[:1787]
location_mapping = {
    'gata4_indirect': 0,
    'gata4_direct': 1
    #'tbx5_indirect': 2,
    #'tbx5_direct': 3,
    #'gata4_tbx5_combo_targets': 4
}
labels_df.rename(columns={'GeneSymbol': 'protein'}, inplace=True)
labels_df['Label'] = labels_df['TF_target_type'].map(location_mapping)
labels_df

protein  TF_target_type  Label
0       DGKG  gata4_indirect      0
1      COPB2  gata4_indirect      0
2       GPX3  gata4_indirect      0
3      DNAH2  gata4_indirect      0
4       TBX4  gata4_indirect      0
...      ...             ...    ...
1783  GPRIN3    gata4_direct      1
1784   LAMA2    gata4_direct      1
1785   CKMT2    gata4_direct      1
1786    FAT3    gata4_direct      1
1787    HTR4    gata4_direct      1

[1787 rows x 3 columns]

In [8]:
#TF_target_type
labels_df = pd.read_csv('GNN/TF_target_type.csv')
labels_df.dropna(inplace=True)
labels_df = labels_df.iloc[1787:]
location_mapping = {
    #'gata4_indirect': 0,
    #'gata4_direct': 1
    'tbx5_indirect': 0,
    'tbx5_direct': 1,
    'gata4_tbx5_combo_targets': 2
}
labels_df.rename(columns={'GeneSymbol': 'protein'}, inplace=True)
labels_df['Label'] = labels_df['TF_target_type'].map(location_mapping)
labels_df

protein            TF_target_type  Label
1788    NARF             tbx5_indirect      0
1789  THNSL1             tbx5_indirect      0
1790   F2RL1             tbx5_indirect      0
1791    GPX8             tbx5_indirect      0
1792  ACADSB             tbx5_indirect      0
...      ...                       ...    ...
4025  GPRIN3  gata4_tbx5_combo_targets      2
4026   LAMA2  gata4_tbx5_combo_targets      2
4027   CKMT2  gata4_tbx5_combo_targets      2
4028    FAT3  gata4_tbx5_combo_targets      2
4029    HTR4  gata4_tbx5_combo_targets      2

[2240 rows x 3 columns]

In [60]:
#phastcons
labels_df = pd.read_csv('GNN/phastcons.csv')
labels_df.dropna(inplace=True)
location_mapping = {
    #'gata4_indirect': 0,
    #'gata4_direct': 1
    'tbx5_indirect': 0,
    'tbx5_direct': 1,
    'gata4_tbx5_combo_targets': 2
}
labels_df.rename(columns={'GeneSymbol': 'protein'}, inplace=True)
labels_df['Label'] = labels_df['TF_target_type'].map(location_mapping)
labels_df

GeneSymbol  Conservation
0           A1BG      0.062761
1           NAT2      0.118469
2            ADA      0.253069
3           CDH2      0.694620
4        GAGE12F      0.088746
...          ...           ...
30992    SLC12A6      0.659845
30993      PTBP3      0.729372
30994      KCNE2      0.160752
30995      DGCR2      0.627946
30996       SCO2      0.229875

[30467 rows x 2 columns]

In [3]:
GO_graph = obonet.read_obo("GNN/go-basic.obo")

go_edges = []
for u, v, data in GO_graph.edges(data=True):
    go_edges.append([u, v])
go_edges_df = pd.DataFrame(go_edges, columns=['Source', 'Target']).dropna()
print(go_edges_df)
col_name = ['GO']
for i in range(1,769):
  col_name.append('feature'+str(i))
go_features_df = pd.read_csv("GNN/go_terms_embeddings.csv", skiprows=1, names=col_name).dropna()
print(go_features_df.head())

           Source      Target
0      GO:0000001  GO:0048308
1      GO:0000001  GO:0048311
2      GO:0000002  GO:0007005
3      GO:0000003  GO:0008150
4      GO:0000006  GO:0005385
...           ...         ...
83792  GO:2001317  GO:0034309
83793  GO:2001317  GO:0042181
83794  GO:2001317  GO:0120255
83795  GO:2001317  GO:1901362
83796  GO:2001317  GO:2001316

[83797 rows x 2 columns]
           GO  feature1  feature2  feature3  feature4  feature5  feature6  \
0  GO:0000001 -1.168093 -0.355214  0.265877 -0.710051  0.515028 -0.525165   
1  GO:0000002 -1.185879 -0.098765  0.388240 -0.295556  0.327296 -0.119842   
2  GO:0000003  0.063323 -0.199995  0.151511 -0.942141  0.109313  0.015316   
3  GO:0000005  0.163135  0.301527  0.219680  0.094342 -0.129769  0.225696   
4  GO:0000006 -0.641113 -0.541363  0.413941  0.699345  0.461507 -0.497388   

   feature7  feature8  feature9  ...  feature759  feature760  feature761  \
0 -0.186588 -0.161192  0.186984  ...   -1.350874   -0.991801   -0.648123   

In [4]:
col_name = ['protein']
for i in range(1,769):
  col_name.append('feature'+str(i))
gene_features_df = pd.read_csv('GNN/gene_embedding_GeneLLM_2.csv', header=None, names=col_name).dropna()
print(gene_features_df.head())

col_name = ['Target', 'Source']
go_protein_df = pd.read_csv(
    "GNN/mart_export.txt", 
    skiprows=1, 
    names=col_name, 
    usecols=[1, 2]  # 使用列的索引来指定
).dropna()
print(go_protein_df)

  protein  feature1  feature2  feature3  feature4  feature5  feature6  \
0     FES  0.339602 -0.030744 -0.901381  0.100888  0.886443  0.383596   
1  HADHA  -0.131799 -0.025745 -0.677301 -0.053545  0.971046  0.180315   
2  SLC7A7  0.385693 -0.070692 -0.847796 -0.022054  0.959772  0.085487   
3    LCK   0.650428  0.014479 -0.866163  0.053508  0.951529  0.269402   
4   HSPA2  0.322262  0.017484 -0.849302  0.046401  0.920429  0.463832   

   feature7  feature8  feature9  ...  feature759  feature760  feature761  \
0 -0.192082 -0.032063 -0.154869  ...   -0.549204   -0.856123    0.714672   
1 -0.028189 -0.077389 -0.095152  ...    0.927885   -0.817812    0.809631   
2  0.076455 -0.003006 -0.032268  ...    0.941094   -0.912443    0.789828   
3 -0.214788  0.045179 -0.506429  ...   -0.576739   -0.969558    0.916549   
4 -0.050414 -0.033398  0.387791  ...    0.387301   -0.860696    0.678607   

   feature762  feature763  feature764  feature765  feature766  feature767  \
0   -0.046649   -0.894424  

In [5]:
print(len(go_features_df))
go_features_df.rename(columns={'GO': 'protein'}, inplace=True)
combined_features = pd.concat([gene_features_df, go_features_df]).reset_index(drop=True)
combined_features

47595


protein  feature1  feature2  feature3  feature4  feature5  feature6  \
0             FES  0.339602 -0.030744 -0.901381  0.100888  0.886443  0.383596   
1          HADHA  -0.131799 -0.025745 -0.677301 -0.053545  0.971046  0.180315   
2          SLC7A7  0.385693 -0.070692 -0.847796 -0.022054  0.959772  0.085487   
3            LCK   0.650428  0.014479 -0.866163  0.053508  0.951529  0.269402   
4           HSPA2  0.322262  0.017484 -0.849302  0.046401  0.920429  0.463832   
...           ...       ...       ...       ...       ...       ...       ...   
62040  GO:2001313  0.174428  0.194728 -0.284376  0.282102 -0.713190 -0.272055   
62041  GO:2001314  0.025886  0.306214 -0.254303  0.253673 -0.533680 -0.269355   
62042  GO:2001315  0.027134  0.241391 -0.227353  0.317366 -0.726657 -0.197968   
62043  GO:2001316  0.139543  0.028883  0.899480  0.152932  0.576852  0.330342   
62044  GO:2001317  0.083064  0.090899  0.888541  0.309920  0.403966  0.202783   

       feature7  feature8  feature9  ...  feature759  feature760  feature761  \
0     -0.192082 -0.032063 -0.154869  ...   -0.549204   -0.856123    0.714672   
1     -0.028189 -0.077389 -0.095152  ...    0.927885   -0.817812    0.809631   
2      0.076455 -0.003006 -0.032268  ...    0.941094   -0.912443    0.789828   
3     -0.214788  0.045179 -0.506429  ...   -0.576739   -0.969558    0.916549   
4     -0.050414 -0.033398  0.387791  ...    0.387301   -0.860696    0.678607   
...         ...       ...       ...  ...         ...         ...         ...   
62040  0.121190  0.129901 -0.983496  ...    0.500545    0.429651   -0.292929   
62041  0.150939 -0.229323 -1.078991  ...    0.042979    0.134560   -0.356661   
62042  0.045653  0.038912 -0.954113  ...    0.349853    0.370059   -0.144606   
62043  0.916943  0.012306 -0.020316  ...   -0.354748   -0.083168    0.043640   
62044  0.706517 -0.017584 -0.171057  ...   -0.544680   -0.046654    0.262865   

       feature762  feature763  feature764  feature765  feature766  feature767  \
0       -0.046649   -0.894424   -0.001815    0.739485    0.015581   -0.023863   
1       -0.005827   -0.848839    0.024516    0.526404   -0.039926   -0.102787   
2        0.046979   -0.715636    0.085842    0.150494    0.025392   -0.066035   
3       -0.080332   -0.927649   -0.047398    0.741663   -0.000096   -0.096318   
4       -0.060695   -0.945793    0.040472    0.831079   -0.001711   -0.079842   
...           ...         ...         ...         ...         ...         ...   
62040   -0.464941   -0.740187    0.179149   -0.960807   -0.746958    1.069112   
62041   -0.381828   -0.638338    0.077176   -0.788312   -0.683442    1.087031   
62042   -0.493184   -0.655063    0.217335   -0.841272   -0.821077    1.036363   
62043   -0.663565    0.543016   -0.652230   -1.427882   -0.985257    1.673561   
62044   -0.767305    0.753788   -0.577503   -1.194910   -0.799556    1.519368   

       feature768  
0       -0.022002  
1       -0.026980  
2       -0.028283  
3       -0.056501  
4       -0.011189  
...           ...  
62040   -0.848182  
62041   -0.593092  
62042   -0.836614  
62043    0.109659  
62044    0.263210  

[62045 rows x 769 columns]

In [6]:
gene_edges_df = pd.read_csv('GNN/protein_interactions.csv', usecols=[0, 1], names=col_name).dropna()

In [7]:
combined_edges = pd.concat([go_protein_df, go_edges_df, gene_edges_df])
#combined_edges = combined_edges[['Source', 'Target']]
combined_edges

Target      Source
0           MT-TF  GO:0030533
1           MT-TF  GO:0006412
4         MT-RNR2  GO:0003735
5         MT-RNR2  GO:0005840
6          MT-TL1  GO:0030533
...           ...         ...
13715124     LDB1      SAMD14
13715125     LDB1       KDM6B
13715126     LDB1        WWP2
13715127     LDB1      VPS33B
13715128     LDB1       NDST2

[13544448 rows x 2 columns]

In [8]:
nodes_in_features = set(combined_features['protein'])

filtered_edges_df = combined_edges[
    combined_edges['Source'].isin(nodes_in_features) & combined_edges['Target'].isin(nodes_in_features)
]


In [9]:
node_id_to_index = {node_id: i for i, node_id in enumerate(combined_features['protein'])}
# 确保edge_index是按照这个新的索引顺序排列的
source_indices = [node_id_to_index[node_id] for node_id in filtered_edges_df['Source']]
target_indices = [node_id_to_index[node_id] for node_id in filtered_edges_df['Target']]
edge_index = torch.tensor([source_indices, target_indices], dtype=torch.long)
edge_index

tensor([[24323, 17460, 27132,  ...,   947,  6874, 13222],
        [ 2077,  2077,  2077,  ..., 10107, 10107, 10107]])

In [10]:
filtered_labels_df = labels_df[
    labels_df['protein'].isin(nodes_in_features)]
filtered_labels_df = filtered_labels_df.reset_index(drop=True)

In [11]:
filtered_labels_df

protein Subcellular_location  Label
0        ORC5              Nucleus      1
1        SFI1            Cytoplasm      2
2      SUCNR1        Cell membrane      0
3        ELK3              Nucleus      1
4       CPEB3            Cytoplasm      2
...       ...                  ...    ...
7698  RPS6KB2            Cytoplasm      2
7699     INSR        Cell membrane      0
7700   SLC7A1        Cell membrane      0
7701  SLC44A2        Cell membrane      0
7702    PARM1        Cell membrane      0

[7703 rows x 3 columns]

In [12]:
label_indices = [node_id_to_index[node_id] for node_id in filtered_labels_df['protein']]
#print(label_indices)
num_nodes = len(combined_features)
labels = torch.full((num_nodes,), -1, dtype=torch.long)
for i, index in enumerate(filtered_labels_df['Label']):
    labels[label_indices[i]] = index

labels_tensor = torch.tensor(labels, dtype=torch.long)

/tmp/ipykernel_1224800/3260523373.py:8: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels_tensor = torch.tensor(labels, dtype=torch.long)


In [13]:
labels

tensor([ 2, -1, -1,  ..., -1, -1, -1])

In [14]:
labels_tensor = torch.tensor(labels, dtype=torch.long)

# 获取 tensor 中不包括 -1 的不同元素
unique_elements = torch.unique(labels_tensor[labels_tensor != -1])
num_unique_elements = unique_elements.numel()

print(f"data.y 中有 {num_unique_elements} 种不同的元素（不包括 -1）")
print("data.y 中的不同元素有（不包括 -1）：")
print(unique_elements)

data.y 中有 3 种不同的元素（不包括 -1）
data.y 中的不同元素有（不包括 -1）：
tensor([0, 1, 2])


/tmp/ipykernel_1224800/306967558.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels_tensor = torch.tensor(labels, dtype=torch.long)


In [15]:
features = combined_features.iloc[:, 1:].values
features_tensor = torch.tensor(features, dtype=torch.float)
features

array([[ 0.33960226, -0.03074448, -0.90138096, ...,  0.01558092,
        -0.02386307, -0.02200161],
       [-0.13179901, -0.02574519, -0.67730105, ..., -0.03992649,
        -0.10278717, -0.02697964],
       [ 0.38569278, -0.07069244, -0.8477959 , ...,  0.0253919 ,
        -0.06603534, -0.02828273],
       ...,
       [ 0.02713387,  0.24139147, -0.22735251, ..., -0.82107705,
         1.036363  , -0.83661443],
       [ 0.13954346,  0.02888298,  0.89947975, ..., -0.9852566 ,
         1.6735605 ,  0.10965873],
       [ 0.08306409,  0.09089889,  0.8885408 , ..., -0.79955566,
         1.5193683 ,  0.2632099 ]])

In [16]:
from torch_geometric.data import Data
data = Data(x=features_tensor, edge_index=edge_index, y=labels_tensor)

print("x:", data.x.shape, data.x.dtype)
print("edge_index:", data.edge_index.shape, data.edge_index.dtype)
print("labels:", data.y.shape, data.y.dtype)

x: torch.Size([62045, 768]) torch.float32
edge_index: torch.Size([2, 9914754]) torch.int64
labels: torch.Size([62045]) torch.int64


In [17]:
from __future__ import division

import torch


def accuracy(pred, target):
    r"""Computes the accuracy of correct predictions.

    Args:
        pred (Tensor): The predictions.
        target (Tensor): The targets.

    :rtype: int
    """
    return (pred == target).sum().item() / target.numel()



def true_positive(pred, target, num_classes):
    r"""Computes the number of true positive predictions.

    Args:
        pred (Tensor): The predictions.
        target (Tensor): The targets.
        num_classes (int): The number of classes.

    :rtype: :class:`LongTensor`
    """
    out = []
    for i in range(num_classes):
        out.append(((pred == i) & (target == i)).sum())

    return torch.tensor(out)



def true_negative(pred, target, num_classes):
    r"""Computes the number of true negative predictions.

    Args:
        pred (Tensor): The predictions.
        target (Tensor): The targets.
        num_classes (int): The number of classes.

    :rtype: :class:`LongTensor`
    """
    out = []
    for i in range(num_classes):
        out.append(((pred != i) & (target != i)).sum())

    return torch.tensor(out)



def false_positive(pred, target, num_classes):
    r"""Computes the number of false positive predictions.

    Args:
        pred (Tensor): The predictions.
        target (Tensor): The targets.
        num_classes (int): The number of classes.

    :rtype: :class:`LongTensor`
    """
    out = []
    for i in range(num_classes):
        out.append(((pred == i) & (target != i)).sum())

    return torch.tensor(out)



def false_negative(pred, target, num_classes):
    r"""Computes the number of false negative predictions.

    Args:
        pred (Tensor): The predictions.
        target (Tensor): The targets.
        num_classes (int): The number of classes.

    :rtype: :class:`LongTensor`
    """
    out = []
    for i in range(num_classes):
        out.append(((pred != i) & (target == i)).sum())

    return torch.tensor(out)



def precision(pred, target, num_classes):
    r"""Computes the precision:
    :math:`\frac{\mathrm{TP}}{\mathrm{TP}+\mathrm{FP}}`.

    Args:
        pred (Tensor): The predictions.
        target (Tensor): The targets.
        num_classes (int): The number of classes.

    :rtype: :class:`Tensor`
    """
    tp = true_positive(pred, target, num_classes).to(torch.float)
    fp = false_positive(pred, target, num_classes).to(torch.float)

    out = tp / (tp + fp)
    out[torch.isnan(out)] = 0

    return out



def recall(pred, target, num_classes):
    r"""Computes the recall:
    :math:`\frac{\mathrm{TP}}{\mathrm{TP}+\mathrm{FN}}`.

    Args:
        pred (Tensor): The predictions.
        target (Tensor): The targets.
        num_classes (int): The number of classes.

    :rtype: :class:`Tensor`
    """
    tp = true_positive(pred, target, num_classes).to(torch.float)
    fn = false_negative(pred, target, num_classes).to(torch.float)

    out = tp / (tp + fn)
    out[torch.isnan(out)] = 0

    return out



def f1_score(pred, target, num_classes):
    r"""Computes the :math:`F_1` score:
    :math:`2 \cdot \frac{\mathrm{precision} \cdot \mathrm{recall}}
    {\mathrm{precision}+\mathrm{recall}}`.

    Args:
        pred (Tensor): The predictions.
        target (Tensor): The targets.
        num_classes (int): The number of classes.

    :rtype: :class:`Tensor`
    """
    prec = precision(pred, target, num_classes)
    rec = recall(pred, target, num_classes)

    score = 2 * (prec * rec) / (prec + rec)
    score[torch.isnan(score)] = 0

    return score

In [18]:

import torch
import torch.nn as nn
from torch_geometric.nn import GCNConv
from torch.nn import ModuleList, Dropout, Linear


class GCN(torch.nn.Module):
    def __init__(self, num_features, hidden_dim, num_classes, num_layers, activation, dropout):
        super(GCN, self).__init__()
        self.conv1 = GCNConv(num_features, hidden_dim)
        self.convs = ModuleList([GCNConv(hidden_dim, hidden_dim) for _ in range(num_layers - 2)])
        self.conv_last = GCNConv(hidden_dim, num_classes)
        self.activation = activation
        self.dropout = Dropout(dropout)
        self.num_layers = num_layers
        self.fc = torch.nn.Linear(hidden_dim, num_classes)
    
    def forward(self, x, edge_index):
        # 输入层
        x = self.conv1(x, edge_index)
        x = self.activation(x)
        x = self.dropout(x)
        
        # 隐藏层
        for conv in self.convs:
            x = conv(x, edge_index)
            x = self.activation(x)
            x = self.dropout(x)

        # 输出层
        #x = self.conv_last(x, edge_index)
        x = self.fc(x)
        return x
    def get_embedding(self, x, edge_index):
        # 输入层
        x = self.conv1(x, edge_index)
        x = self.activation(x)
        x = self.dropout(x)
        
        # 隐藏层
        for conv in self.convs:
            x = conv(x, edge_index)
            x = self.activation(x)
            x = self.dropout(x)
        return x

In [19]:
from sklearn.preprocessing import label_binarize
def train_model_scheduler(model, masked_features, labels, edge_index, optimizer, criterion, scheduler, train_mask):
    model.train()  # 设置模型为训练模
    optimizer.zero_grad()  # 清空梯度
    out = model(masked_features, edge_index)  # 获取模型输出
    loss = criterion(out[train_mask], data.y[train_mask])  # 计算损失值，只针对训练集的节点
    loss.backward()  # 反向传播
    optimizer.step()  # 更新模型参数
    scheduler.step(loss)
    return loss.item()

def train_model(model, masked_features, labels, edge_index, optimizer, criterion, train_mask):
    model.train()  # 设置模型为训练模式
    optimizer.zero_grad()  # 清空梯度
    out = model(masked_features, edge_index) # 获取模型输出
    loss = criterion(out[train_mask], data.y[train_mask])  # 计算损失值，只针对训练集的节点
    loss.backward()  # 反向传播
    optimizer.step()  # 更新模型参数
    return loss.item()
"""
def evaluate_model(model, features, labels, edge_index, mask):
    model.eval()  # 设置模型为评估模式
    with torch.no_grad():  # 关闭梯度计算
        # 获取模型输出，这里假设输出已经是经过sigmoid的概率
        probabilities = model(features, edge_index)
        predictions = torch.argmax(probabilities[mask], dim=1)  # 获取预测类别
        
        # F1 分数 - 宏平均
        val_f1 = f1_score(labels[mask].cpu().numpy(), predictions.cpu().numpy(), average='macro')
        
        # 多分类AUC计算（一对多方法）
        auc_score = 0
        for class_idx in range(probabilities.shape[1]):  # 遍历每个类别
            true_binary = (labels[mask] == class_idx).cpu().numpy()  # 当前类别为正类，其他类别为负类
            pred_probs = probabilities[mask, class_idx].cpu().numpy()  # 当前类别的预测概率
            auc_score += roc_auc_score(true_binary, pred_probs)  # 计算当前类别的AUC
        
        # 计算平均AUC
        auc_score /= probabilities.shape[1]

    return val_f1, auc_score"""
def evaluate_model(model, features, labels, edge_index, mask):
    model.eval()  # 设置模型为评估模式
    with torch.no_grad():  # 关闭梯度计算
        # 获取模型输出，这里假设输出已经是经过sigmoid的概率
        probabilities = model(features, edge_index)
        predictions = torch.argmax(probabilities[mask], dim=1)  # 获取预测类别
        auc_score = 0
        for class_idx in range(probabilities.shape[1]):  # 遍历每个类别
            true_binary = (labels[mask] == class_idx).cpu().numpy()  # 当前类别为正类，其他类别为负类
            pred_probs = probabilities[mask, class_idx].cpu().numpy()  # 当前类别的预测概率
            auc_score += roc_auc_score(true_binary, pred_probs)  # 计算当前类别的AUC
        
        # 计算平均AUC
        auc_score /= probabilities.shape[1]

        val_f1 = torch.mean(f1_score(torch.argmax(probabilities[mask],dim=1), labels[mask], num_classes=3)).cpu().numpy()
        #auc_score = roc_auc_score(labels[mask].cpu().numpy(), positive_probs.cpu().numpy())

    return val_f1, auc_score

In [20]:
#localization
from sklearn.metrics import roc_auc_score
import numpy as np
import random
import torch.nn.functional as F
from sklearn.model_selection import train_test_split

import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
resilt_localization = []
for x in range(5):
    # 实例化模型
    device = torch.device('cuda:1')
    data = data.to(device)
    model = GCN(num_features=768, hidden_dim=64, num_classes=3, num_layers=3, activation=F.relu, dropout=0.5)
    model.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=0.001)
    loss_fn = torch.nn.CrossEntropyLoss()
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.2, patience=50, verbose=True)
    
    labeled_indices = label_indices
    random.shuffle(labeled_indices)
    num_labeled = len(labeled_indices)
    num_train = int(num_labeled * 0.8)
    num_test = num_labeled - num_train
    print(num_test)
    
    # 创建训练和测试掩码
    train_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
    test_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
    
    train_mask[labeled_indices[:num_train]] = True
    test_mask[labeled_indices[num_train:num_train+num_test]] = True
    print(test_mask)
    #fully connection
    """
    num_epochs = 1000
    x_type1 = data.x[:14450]
    x_type2 = data.x[14450:]
    x_list = [x_type1, x_type2]
    for epoch in range(num_epochs):
        train_loss = train_model_scheduler(model, data.x, data.y, data.edge_index, optimizer, loss_fn, scheduler, train_mask)
        test_f1, test_auc = evaluate_model(model, data.x, data.y, data.edge_index, test_mask)
        
        if (epoch + 1) % 50 == 0: 
            print(f'Epoch {epoch}: Train Loss:{train_loss:.4f}, Macro_F1: {test_f1:.4f}, AUC_score: {test_auc:.4f}')
    resilt_localization.append({'F1': test_f1,
                    'AUC_score': test_auc})"""

1541
tensor([ True, False, False,  ..., False, False, False])
1541
tensor([False, False, False,  ..., False, False, False])
1541
tensor([ True, False, False,  ..., False, False, False])
1541
tensor([False, False, False,  ..., False, False, False])
1541
tensor([ True, False, False,  ..., False, False, False])


In [22]:
resilt_localization

[{'F1': array(0.8575546, dtype=float32), 'AUC_score': 0.9388644856089505},
 {'F1': array(0.86176014, dtype=float32), 'AUC_score': 0.9444933915799559},
 {'F1': array(0.8658428, dtype=float32), 'AUC_score': 0.946029501826635},
 {'F1': array(0.881814, dtype=float32), 'AUC_score': 0.950830882457491},
 {'F1': array(0.8532157, dtype=float32), 'AUC_score': 0.9430605067229267}]

In [32]:
#DosageSensitivity
from sklearn.metrics import roc_auc_score
import numpy as np
import random
import torch.nn.functional as F
from sklearn.model_selection import train_test_split

import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
result_DosageSensitivity = []
for x in range(5):
    # 实例化模型
    device = torch.device('cuda:1')
    data = data.to(device)
    model = GCN(num_features=768, hidden_dim=64, num_classes=2, num_layers=3, activation=F.relu, dropout=0.5)
    model.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=0.001)
    loss_fn = torch.nn.CrossEntropyLoss()
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.2, patience=50, verbose=True)
    
    labeled_indices = label_indices
    random.shuffle(labeled_indices)
    num_labeled = len(labeled_indices)
    num_train = int(num_labeled * 0.8)
    num_test = num_labeled - num_train
    print(num_test)
    
    # 创建训练和测试掩码
    train_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
    test_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
    
    train_mask[labeled_indices[:num_train]] = True
    test_mask[labeled_indices[num_train:num_train+num_test]] = True
    print(test_mask)
    #fully connection
    num_epochs = 1000
    x_type1 = data.x[:14450]
    x_type2 = data.x[14450:]
    x_list = [x_type1, x_type2]
    for epoch in range(num_epochs):
        train_loss = train_model_scheduler(model, data.x, data.y, data.edge_index, optimizer, loss_fn, scheduler, train_mask)
        test_f1, test_auc = evaluate_model(model, data.x, data.y, data.edge_index, test_mask)
        
        if (epoch + 1) % 50 == 0: 
            print(f'Epoch {epoch}: Train Loss:{train_loss:.4f}, Macro_F1: {test_f1:.4f}, AUC_score: {test_auc:.4f}')
    result_DosageSensitivity.append({'F1': test_f1,
                    'AUC_score': test_auc})
print(result_DosageSensitivity)

57
tensor([False, False, False,  ..., False, False, False])
Epoch 49: Train Loss:0.3885, Macro_F1: 0.8178, AUC_score: 0.8721
Epoch 99: Train Loss:0.3355, Macro_F1: 0.8348, AUC_score: 0.8818
Epoch 149: Train Loss:0.2737, Macro_F1: 0.8149, AUC_score: 0.8922
Epoch 199: Train Loss:0.2311, Macro_F1: 0.8492, AUC_score: 0.8942
Epoch 249: Train Loss:0.1804, Macro_F1: 0.8492, AUC_score: 0.8766
Epoch 299: Train Loss:0.1427, Macro_F1: 0.8201, AUC_score: 0.9110
Epoch 349: Train Loss:0.1444, Macro_F1: 0.8519, AUC_score: 0.8987
Epoch 399: Train Loss:0.1165, Macro_F1: 0.8519, AUC_score: 0.8935
Epoch 449: Train Loss:0.1203, Macro_F1: 0.8348, AUC_score: 0.8987
Epoch 499: Train Loss:0.0841, Macro_F1: 0.8693, AUC_score: 0.8935
Epoch 549: Train Loss:0.1089, Macro_F1: 0.8348, AUC_score: 0.8929
Epoch 599: Train Loss:0.0920, Macro_F1: 0.8519, AUC_score: 0.8890
Epoch 649: Train Loss:0.0754, Macro_F1: 0.8519, AUC_score: 0.8844
Epoch 00679: reducing learning rate of group 0 to 2.0000e-04.
Epoch 699: Train Loss:

In [42]:
#BivalentVsLys4
from sklearn.metrics import roc_auc_score
import numpy as np
import random
import torch.nn.functional as F
from sklearn.model_selection import train_test_split

import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
result_BivalentVsLys4 = []
for x in range(5):
    # 实例化模型
    device = torch.device('cuda:1')
    data = data.to(device)
    model = GCN(num_features=768, hidden_dim=64, num_classes=2, num_layers=3, activation=F.relu, dropout=0.5)
    model.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=0.001)
    loss_fn = torch.nn.CrossEntropyLoss()
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.2, patience=50, verbose=True)
    
    labeled_indices = label_indices
    random.shuffle(labeled_indices)
    num_labeled = len(labeled_indices)
    num_train = int(num_labeled * 0.8)
    num_test = num_labeled - num_train
    print(num_test)
    
    # 创建训练和测试掩码
    train_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
    test_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
    
    train_mask[labeled_indices[:num_train]] = True
    test_mask[labeled_indices[num_train:num_train+num_test]] = True
    print(test_mask)
    #fully connection
    num_epochs = 1000
    x_type1 = data.x[:14450]
    x_type2 = data.x[14450:]
    x_list = [x_type1, x_type2]
    for epoch in range(num_epochs):
        train_loss = train_model_scheduler(model, data.x, data.y, data.edge_index, optimizer, loss_fn, scheduler, train_mask)
        test_f1, test_auc = evaluate_model(model, data.x, data.y, data.edge_index, test_mask)
        
        if (epoch + 1) % 50 == 0: 
            print(f'Epoch {epoch}: Train Loss:{train_loss:.4f}, Macro_F1: {test_f1:.4f}, AUC_score: {test_auc:.4f}')
    result_BivalentVsLys4.append({'F1': test_f1,
                    'AUC_score': test_auc})
print(result_BivalentVsLys4)

34
tensor([False, False, False,  ..., False, False, False])
Epoch 49: Train Loss:0.3229, Macro_F1: 0.9699, AUC_score: 0.9930
Epoch 99: Train Loss:0.1598, Macro_F1: 0.9699, AUC_score: 0.9439
Epoch 149: Train Loss:0.1060, Macro_F1: 0.9111, AUC_score: 0.9386
Epoch 199: Train Loss:0.0430, Macro_F1: 0.9393, AUC_score: 0.9228
Epoch 249: Train Loss:0.0374, Macro_F1: 0.9393, AUC_score: 0.9211
Epoch 299: Train Loss:0.0734, Macro_F1: 0.9393, AUC_score: 0.9035
Epoch 00320: reducing learning rate of group 0 to 2.0000e-04.
Epoch 349: Train Loss:0.0199, Macro_F1: 0.9098, AUC_score: 0.9140
Epoch 00387: reducing learning rate of group 0 to 4.0000e-05.
Epoch 399: Train Loss:0.0224, Macro_F1: 0.9393, AUC_score: 0.9070
Epoch 00441: reducing learning rate of group 0 to 8.0000e-06.
Epoch 449: Train Loss:0.0100, Macro_F1: 0.9393, AUC_score: 0.9053
Epoch 00492: reducing learning rate of group 0 to 1.6000e-06.
Epoch 499: Train Loss:0.0181, Macro_F1: 0.9393, AUC_score: 0.9035
Epoch 00543: reducing learning rat

In [51]:

#BivalentVsNonMethylated
from sklearn.metrics import roc_auc_score
import numpy as np
import random
import torch.nn.functional as F
from sklearn.model_selection import train_test_split

import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
result_BivalentVsNonMethylated = []
for x in range(5):
    # 实例化模型
    device = torch.device('cuda:1')
    data = data.to(device)
    model = GCN(num_features=768, hidden_dim=64, num_classes=2, num_layers=3, activation=F.relu, dropout=0.5)
    model.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=0.001)
    loss_fn = torch.nn.CrossEntropyLoss()
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.2, patience=50, verbose=True)
    
    labeled_indices = label_indices
    random.shuffle(labeled_indices)
    num_labeled = len(labeled_indices)
    num_train = int(num_labeled * 0.8)
    num_test = num_labeled - num_train
    print(num_test)
    
    # 创建训练和测试掩码
    train_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
    test_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
    
    train_mask[labeled_indices[:num_train]] = True
    test_mask[labeled_indices[num_train:num_train+num_test]] = True
    print(test_mask)
    #fully connection
    num_epochs = 650
    x_type1 = data.x[:14450]
    x_type2 = data.x[14450:]
    x_list = [x_type1, x_type2]
    for epoch in range(num_epochs):
        train_loss = train_model_scheduler(model, data.x, data.y, data.edge_index, optimizer, loss_fn, scheduler, train_mask)
        test_f1, test_auc = evaluate_model(model, data.x, data.y, data.edge_index, test_mask)
        
        if (epoch + 1) % 50 == 0: 
            print(f'Epoch {epoch}: Train Loss:{train_loss:.4f}, Macro_F1: {test_f1:.4f}, AUC_score: {test_auc:.4f}')
    result_BivalentVsNonMethylated.append({'F1': test_f1,
                    'AUC_score': test_auc})
print(result_BivalentVsNonMethylated)

26
tensor([False, False, False,  ..., False, False, False])
Epoch 49: Train Loss:0.3054, Macro_F1: 0.7984, AUC_score: 0.9458
Epoch 99: Train Loss:0.1780, Macro_F1: 0.8762, AUC_score: 0.9250
Epoch 149: Train Loss:0.0599, Macro_F1: 0.7984, AUC_score: 0.9667
Epoch 199: Train Loss:0.0575, Macro_F1: 0.7984, AUC_score: 0.9875
Epoch 249: Train Loss:0.0186, Macro_F1: 1.0000, AUC_score: 1.0000
Epoch 299: Train Loss:0.0104, Macro_F1: 0.9424, AUC_score: 1.0000
Epoch 349: Train Loss:0.0176, Macro_F1: 0.9424, AUC_score: 1.0000
Epoch 399: Train Loss:0.0136, Macro_F1: 0.9424, AUC_score: 1.0000
Epoch 449: Train Loss:0.0049, Macro_F1: 0.9424, AUC_score: 1.0000
Epoch 00489: reducing learning rate of group 0 to 2.0000e-04.
Epoch 499: Train Loss:0.0048, Macro_F1: 0.9424, AUC_score: 1.0000
Epoch 549: Train Loss:0.0059, Macro_F1: 0.9424, AUC_score: 1.0000
Epoch 599: Train Loss:0.0066, Macro_F1: 0.9424, AUC_score: 1.0000
Epoch 649: Train Loss:0.0078, Macro_F1: 0.9424, AUC_score: 1.0000
26
tensor([False, Fals

In [60]:
#Tf_range
from sklearn.metrics import roc_auc_score
import numpy as np
import random
import torch.nn.functional as F
from sklearn.model_selection import train_test_split

import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
result_Tf_range = []
for x in range(5):
    # 实例化模型
    device = torch.device('cuda:1')
    data = data.to(device)
    model = GCN(num_features=768, hidden_dim=64, num_classes=2, num_layers=4, activation=F.relu, dropout=0.5)
    model.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=0.001)
    loss_fn = torch.nn.CrossEntropyLoss()
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.2, patience=50, verbose=True)
    
    labeled_indices = label_indices
    random.shuffle(labeled_indices)
    num_labeled = len(labeled_indices)
    num_train = int(num_labeled * 0.8)
    num_test = num_labeled - num_train
    print(num_test)
    
    # 创建训练和测试掩码
    train_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
    test_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
    
    train_mask[labeled_indices[:num_train]] = True
    test_mask[labeled_indices[num_train:num_train+num_test]] = True
    print(test_mask)
    
    num_epochs = 650
    
    for epoch in range(num_epochs):
        train_loss = train_model_scheduler(model, data.x, data.y, data.edge_index, optimizer, loss_fn, scheduler, train_mask)
        test_f1, test_auc = evaluate_model(model, data.x, data.y, data.edge_index, test_mask)
        
        if (epoch + 1) % 20 == 0: 
            print(f'Epoch {epoch}: Train Loss:{train_loss:.4f}, Macro_F1: {test_f1:.4f}, AUC_score: {test_auc:.4f}')
    result_Tf_range.append({'F1': test_f1,
                    'AUC_score': test_auc})
print(result_Tf_range)

32
tensor([False, False, False,  ..., False, False, False])
Epoch 19: Train Loss:0.5641, Macro_F1: 0.3962, AUC_score: 0.4048
Epoch 39: Train Loss:0.5189, Macro_F1: 0.3962, AUC_score: 0.4372
Epoch 59: Train Loss:0.4644, Macro_F1: 0.3962, AUC_score: 0.4632
Epoch 79: Train Loss:0.3750, Macro_F1: 0.4872, AUC_score: 0.4913
Epoch 99: Train Loss:0.3394, Macro_F1: 0.5152, AUC_score: 0.5152
Epoch 119: Train Loss:0.3189, Macro_F1: 0.3962, AUC_score: 0.5108
Epoch 139: Train Loss:0.3418, Macro_F1: 0.4514, AUC_score: 0.5779
Epoch 159: Train Loss:0.1993, Macro_F1: 0.7091, AUC_score: 0.6061
Epoch 179: Train Loss:0.1925, Macro_F1: 0.6811, AUC_score: 0.6299
Epoch 199: Train Loss:0.1070, Macro_F1: 0.5636, AUC_score: 0.5844
Epoch 219: Train Loss:0.0830, Macro_F1: 0.5883, AUC_score: 0.5649
Epoch 239: Train Loss:0.0803, Macro_F1: 0.6537, AUC_score: 0.6104
Epoch 259: Train Loss:0.0792, Macro_F1: 0.6135, AUC_score: 0.6147
Epoch 279: Train Loss:0.0745, Macro_F1: 0.6811, AUC_score: 0.6623
Epoch 299: Train Loss

In [72]:
#TF_target_type
from sklearn.metrics import roc_auc_score
import numpy as np
import random
import torch.nn.functional as F
from sklearn.model_selection import train_test_split

import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
result_Tftarget_type1 = []
for x in range(5):
# 实例化模型
    device = torch.device('cuda:1')
    data = data.to(device)
    model = GCN(num_features=768, hidden_dim=64, num_classes=2, num_layers=5, activation=F.relu, dropout=0.5)
    model.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.1, weight_decay=0.001)
    loss_fn = torch.nn.CrossEntropyLoss()
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.2, patience=50, verbose=True)
    
    labeled_indices = label_indices
    random.shuffle(labeled_indices)
    num_labeled = len(labeled_indices)
    num_train = int(num_labeled * 0.8)
    num_test = num_labeled - num_train
    print(num_test)
    
    # 创建训练和测试掩码
    train_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
    test_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
    
    train_mask[labeled_indices[:num_train]] = True
    test_mask[labeled_indices[num_train:num_train+num_test]] = True
    print(test_mask)
    
    num_epochs = 500
    
    for epoch in range(num_epochs):
        train_loss = train_model_scheduler(model, data.x, data.y, data.edge_index, optimizer, loss_fn, scheduler, train_mask)
        test_f1, test_auc = evaluate_model(model, data.x, data.y, data.edge_index, test_mask)
        
        if (epoch + 1) % 20 == 0: 
            print(f'Epoch {epoch}: Train Loss:{train_loss:.4f}, Macro_F1: {test_f1:.4f}, AUC_score: {test_auc:.4f}')
    result_Tftarget_type1.append({'F1': test_f1,
                    'AUC_score': test_auc})
print(result_Tftarget_type1)

277
tensor([False, False, False,  ..., False, False, False])
Epoch 19: Train Loss:0.6275, Macro_F1: 0.4004, AUC_score: 0.5025
Epoch 39: Train Loss:0.6281, Macro_F1: 0.4017, AUC_score: 0.5000
Epoch 59: Train Loss:0.6375, Macro_F1: 0.4017, AUC_score: 0.5237
Epoch 00068: reducing learning rate of group 0 to 2.0000e-02.
Epoch 79: Train Loss:0.6233, Macro_F1: 0.4017, AUC_score: 0.5000
Epoch 99: Train Loss:0.6244, Macro_F1: 0.4017, AUC_score: 0.5000
Epoch 00119: reducing learning rate of group 0 to 4.0000e-03.
Epoch 119: Train Loss:0.6242, Macro_F1: 0.4017, AUC_score: 0.5000
Epoch 139: Train Loss:0.6232, Macro_F1: 0.4017, AUC_score: 0.5000
Epoch 159: Train Loss:0.6242, Macro_F1: 0.4017, AUC_score: 0.5000
Epoch 00170: reducing learning rate of group 0 to 8.0000e-04.
Epoch 179: Train Loss:0.6223, Macro_F1: 0.4017, AUC_score: 0.5000
Epoch 199: Train Loss:0.6242, Macro_F1: 0.4017, AUC_score: 0.5000
Epoch 219: Train Loss:0.6242, Macro_F1: 0.4017, AUC_score: 0.5000
Epoch 00221: reducing learning r

In [58]:
#TF_target_type
from sklearn.metrics import roc_auc_score
import numpy as np
import random
import torch.nn.functional as F
from sklearn.model_selection import train_test_split

import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
result_Tftarget_type2 = []
for x in range(5):
# 实例化模型
    device = torch.device('cuda:1')
    data = data.to(device)
    model = GCN(num_features=768, hidden_dim=64, num_classes=3, num_layers=5, activation=F.relu, dropout=0.5)
    model.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.1, weight_decay=0.001)
    loss_fn = torch.nn.CrossEntropyLoss()
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.2, patience=50, verbose=True)
    
    labeled_indices = label_indices
    random.shuffle(labeled_indices)
    num_labeled = len(labeled_indices)
    num_train = int(num_labeled * 0.8)
    num_test = num_labeled - num_train
    print(num_test)
    
    # 创建训练和测试掩码
    train_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
    test_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
    
    train_mask[labeled_indices[:num_train]] = True
    test_mask[labeled_indices[num_train:num_train+num_test]] = True
    print(test_mask)
    
    num_epochs = 500
    
    for epoch in range(num_epochs):
        train_loss = train_model_scheduler(model, data.x, data.y, data.edge_index, optimizer, loss_fn, scheduler, train_mask)
        test_f1, test_auc = evaluate_model(model, data.x, data.y, data.edge_index, test_mask)
        
        if (epoch + 1) % 20 == 0: 
            print(f'Epoch {epoch}: Train Loss:{train_loss:.4f}, Macro_F1: {test_f1:.4f}, AUC_score: {test_auc:.4f}')
        result_Tftarget_type2.append({'F1': test_f1,
                    'AUC_score': test_auc})
print(result_Tftarget_type2)

351
tensor([False, False, False,  ..., False, False, False])
Epoch 19: Train Loss:1.0360, Macro_F1: 0.2676, AUC_score: 0.5525
Epoch 39: Train Loss:1.0411, Macro_F1: 0.2066, AUC_score: 0.4949
Epoch 59: Train Loss:1.0399, Macro_F1: 0.2066, AUC_score: 0.4798
Epoch 00071: reducing learning rate of group 0 to 2.0000e-02.
Epoch 79: Train Loss:1.0403, Macro_F1: 0.2066, AUC_score: 0.4987
Epoch 99: Train Loss:1.0400, Macro_F1: 0.2066, AUC_score: 0.4859
Epoch 119: Train Loss:1.0391, Macro_F1: 0.2066, AUC_score: 0.4975
Epoch 00122: reducing learning rate of group 0 to 4.0000e-03.
Epoch 139: Train Loss:1.0392, Macro_F1: 0.2066, AUC_score: 0.5000
Epoch 159: Train Loss:1.0392, Macro_F1: 0.2066, AUC_score: 0.5000
Epoch 00173: reducing learning rate of group 0 to 8.0000e-04.
Epoch 179: Train Loss:1.0392, Macro_F1: 0.2066, AUC_score: 0.5000
Epoch 199: Train Loss:1.0392, Macro_F1: 0.2066, AUC_score: 0.5000
Epoch 219: Train Loss:1.0392, Macro_F1: 0.2066, AUC_score: 0.5000
Epoch 00224: reducing learning r

In [21]:
labeled_indices = label_indices
labeled_indices

[4153,
 11097,
 3849,
 518,
 12611,
 10339,
 10138,
 4498,
 12436,
 9062,
 5846,
 934,
 10114,
 6054,
 8789,
 10620,
 7708,
 11433,
 10756,
 13879,
 3709,
 11443,
 2262,
 4593,
 3594,
 2137,
 10713,
 7868,
 742,
 13130,
 3661,
 1110,
 2459,
 3098,
 6765,
 5337,
 12284,
 2695,
 3760,
 3567,
 8094,
 4471,
 4372,
 13021,
 12447,
 8875,
 7800,
 9753,
 10997,
 11250,
 14267,
 5431,
 7828,
 13572,
 7378,
 3437,
 593,
 10603,
 5358,
 357,
 5268,
 8199,
 6790,
 10924,
 1461,
 3986,
 3701,
 9344,
 463,
 245,
 1453,
 3607,
 2318,
 4057,
 6998,
 4084,
 7890,
 1972,
 2665,
 204,
 9403,
 8449,
 13789,
 4977,
 8530,
 10742,
 2478,
 72,
 11298,
 12014,
 9878,
 8007,
 8073,
 5890,
 9935,
 11423,
 11712,
 14054,
 1539,
 8482,
 5598,
 11238,
 5027,
 777,
 5759,
 6176,
 13685,
 9112,
 4504,
 5384,
 6352,
 5114,
 13011,
 4722,
 12358,
 14259,
 6109,
 5428,
 4430,
 10711,
 4702,
 9928,
 12990,
 8739,
 10969,
 94,
 13067,
 10507,
 606,
 10204,
 4017,
 3850,
 4542,
 6368,
 5660,
 6138,
 1343,
 13594,
 14226,

In [22]:
import numpy as np
train_indices = labeled_indices[:num_train]
test_indices = labeled_indices[num_train:num_train+num_test]
print(train_indices)
print(test_indices)

[4153, 11097, 3849, 518, 12611, 10339, 10138, 4498, 12436, 9062, 5846, 934, 10114, 6054, 8789, 10620, 7708, 11433, 10756, 13879, 3709, 11443, 2262, 4593, 3594, 2137, 10713, 7868, 742, 13130, 3661, 1110, 2459, 3098, 6765, 5337, 12284, 2695, 3760, 3567, 8094, 4471, 4372, 13021, 12447, 8875, 7800, 9753, 10997, 11250, 14267, 5431, 7828, 13572, 7378, 3437, 593, 10603, 5358, 357, 5268, 8199, 6790, 10924, 1461, 3986, 3701, 9344, 463, 245, 1453, 3607, 2318, 4057, 6998, 4084, 7890, 1972, 2665, 204, 9403, 8449, 13789, 4977, 8530, 10742, 2478, 72, 11298, 12014, 9878, 8007, 8073, 5890, 9935, 11423, 11712, 14054, 1539, 8482, 5598, 11238, 5027, 777, 5759, 6176, 13685, 9112, 4504, 5384, 6352, 5114, 13011, 4722, 12358, 14259, 6109, 5428, 4430, 10711, 4702, 9928, 12990, 8739, 10969, 94, 13067, 10507, 606, 10204, 4017, 3850, 4542, 6368, 5660, 6138, 1343, 13594, 14226, 10914, 11232, 884, 6502, 119, 2769, 4024, 7650, 14100, 1926, 8295, 6915, 8150, 7230, 2996, 7389, 10126, 6434, 11302, 7291, 3102, 12126, 6

In [30]:
combined_features

protein  feature1  feature2  feature3  feature4  feature5  feature6  \
0             FES  0.339602 -0.030744 -0.901381  0.100888  0.886443  0.383596   
1          HADHA  -0.131799 -0.025745 -0.677301 -0.053545  0.971046  0.180315   
2          SLC7A7  0.385693 -0.070692 -0.847796 -0.022054  0.959772  0.085487   
3            LCK   0.650428  0.014479 -0.866163  0.053508  0.951529  0.269402   
4           HSPA2  0.322262  0.017484 -0.849302  0.046401  0.920429  0.463832   
...           ...       ...       ...       ...       ...       ...       ...   
62040  GO:2001313  0.174428  0.194728 -0.284376  0.282102 -0.713190 -0.272055   
62041  GO:2001314  0.025886  0.306214 -0.254303  0.253673 -0.533680 -0.269355   
62042  GO:2001315  0.027134  0.241391 -0.227353  0.317366 -0.726657 -0.197968   
62043  GO:2001316  0.139543  0.028883  0.899480  0.152932  0.576852  0.330342   
62044  GO:2001317  0.083064  0.090899  0.888541  0.309920  0.403966  0.202783   

       feature7  feature8  feature9  ...  feature759  feature760  feature761  \
0     -0.192082 -0.032063 -0.154869  ...   -0.549204   -0.856123    0.714672   
1     -0.028189 -0.077389 -0.095152  ...    0.927885   -0.817812    0.809631   
2      0.076455 -0.003006 -0.032268  ...    0.941094   -0.912443    0.789828   
3     -0.214788  0.045179 -0.506429  ...   -0.576739   -0.969558    0.916549   
4     -0.050414 -0.033398  0.387791  ...    0.387301   -0.860696    0.678607   
...         ...       ...       ...  ...         ...         ...         ...   
62040  0.121190  0.129901 -0.983496  ...    0.500545    0.429651   -0.292929   
62041  0.150939 -0.229323 -1.078991  ...    0.042979    0.134560   -0.356661   
62042  0.045653  0.038912 -0.954113  ...    0.349853    0.370059   -0.144606   
62043  0.916943  0.012306 -0.020316  ...   -0.354748   -0.083168    0.043640   
62044  0.706517 -0.017584 -0.171057  ...   -0.544680   -0.046654    0.262865   

       feature762  feature763  feature764  feature765  feature766  feature767  \
0       -0.046649   -0.894424   -0.001815    0.739485    0.015581   -0.023863   
1       -0.005827   -0.848839    0.024516    0.526404   -0.039926   -0.102787   
2        0.046979   -0.715636    0.085842    0.150494    0.025392   -0.066035   
3       -0.080332   -0.927649   -0.047398    0.741663   -0.000096   -0.096318   
4       -0.060695   -0.945793    0.040472    0.831079   -0.001711   -0.079842   
...           ...         ...         ...         ...         ...         ...   
62040   -0.464941   -0.740187    0.179149   -0.960807   -0.746958    1.069112   
62041   -0.381828   -0.638338    0.077176   -0.788312   -0.683442    1.087031   
62042   -0.493184   -0.655063    0.217335   -0.841272   -0.821077    1.036363   
62043   -0.663565    0.543016   -0.652230   -1.427882   -0.985257    1.673561   
62044   -0.767305    0.753788   -0.577503   -1.194910   -0.799556    1.519368   

       feature768  
0       -0.022002  
1       -0.026980  
2       -0.028283  
3       -0.056501  
4       -0.011189  
...           ...  
62040   -0.848182  
62041   -0.593092  
62042   -0.836614  
62043    0.109659  
62044    0.263210  

[62045 rows x 769 columns]

In [24]:
num_nodes

62045

In [25]:
num_iterations = 100
count = 1 / num_iterations

# 总节点数
num_nodes = data.x.shape[0]
# 所有节点的索引
all_indices = np.arange(num_nodes)
mask_out = torch.ones(num_nodes, dtype=torch.bool)
# 将测试集索引处的掩码设为False
#mask_out[test_indices] = False
end = len(combined_features) #- 47595
#mask_out[-47595:] = False
mask_out[0:end] = False
# 使用掩码获取剩余的索引
remaining_indices = all_indices[mask_out]
complement_mask = ~mask_out
#complement_mask[test_indices] = False

# 得到既不在 remaining_indices 也不在 test_indices 中的索引
complement_indices = all_indices[complement_mask]
print(len(complement_indices))

62045


In [26]:
num_nodes_out = len(complement_indices)
num_to_select = int(num_nodes_out * count)
for i in range(num_iterations+1):
    if i > 0:
    # 随机选择节点
        selected_indices = np.random.choice(complement_indices, num_to_select, replace=False)
        # 更新剩余节点列表
        complement_indices = np.setdiff1d(complement_indices, selected_indices)
    else:
        selected_indices = np.random.choice(complement_indices, 0, replace=False)
        complement_indices = np.setdiff1d(complement_indices, selected_indices)
    print("c:",len(complement_indices))
    # 保存到文件
    print("s:",len(selected_indices))
    np.save(f'DIVIDED_DATA/GOwith_{i}%.npy', complement_indices)  # 修改保存路径

print("所有迭代的selected_indices和remaining_indices已保存到文件。")

c: 62045
s: 0
c: 61425
s: 620
c: 60805
s: 620
c: 60185
s: 620
c: 59565
s: 620
c: 58945
s: 620
c: 58325
s: 620
c: 57705
s: 620
c: 57085
s: 620
c: 56465
s: 620
c: 55845
s: 620
c: 55225
s: 620
c: 54605
s: 620
c: 53985
s: 620
c: 53365
s: 620
c: 52745
s: 620
c: 52125
s: 620
c: 51505
s: 620
c: 50885
s: 620
c: 50265
s: 620
c: 49645
s: 620
c: 49025
s: 620
c: 48405
s: 620
c: 47785
s: 620
c: 47165
s: 620
c: 46545
s: 620
c: 45925
s: 620
c: 45305
s: 620
c: 44685
s: 620
c: 44065
s: 620
c: 43445
s: 620
c: 42825
s: 620
c: 42205
s: 620
c: 41585
s: 620
c: 40965
s: 620
c: 40345
s: 620
c: 39725
s: 620
c: 39105
s: 620
c: 38485
s: 620
c: 37865
s: 620
c: 37245
s: 620
c: 36625
s: 620
c: 36005
s: 620
c: 35385
s: 620
c: 34765
s: 620
c: 34145
s: 620
c: 33525
s: 620
c: 32905
s: 620
c: 32285
s: 620
c: 31665
s: 620
c: 31045
s: 620
c: 30425
s: 620
c: 29805
s: 620
c: 29185
s: 620
c: 28565
s: 620
c: 27945
s: 620
c: 27325
s: 620
c: 26705
s: 620
c: 26085
s: 620
c: 25465
s: 620
c: 24845
s: 620
c: 24225
s: 620
c: 23605
s

In [27]:
class EarlyStopping:
    """早停机制，用于在验证损失停止改善时终止训练。"""
    def __init__(self, patience=200, verbose=False, delta=0):
        """
        参数:
            patience (int): 损失没有改善的迭代次数，在这之后训练将会被停止。
            verbose (bool): 如果为True，则打印一条消息表明早停被触发。
            delta (float): 损失的最小改变，被认为是改善。
            path (str): 最佳模型保存路径。
        """
        self.patience = patience
        self.verbose = verbose
        self.delta = delta
        self.best_loss = None
        self.early_stop = False
        self.counter = 0

    def __call__(self, val_loss, model, path):
        if self.best_loss is None:
            self.best_loss = val_loss
            self.save_checkpoint(val_loss, model, path)
        elif val_loss > self.best_loss - self.delta:
            self.counter += 1
            if self.counter >= self.patience:
                self.early_stop = True
                if self.verbose:
                    print("Early stopping triggered")
        else:
            self.best_loss = val_loss
            self.save_checkpoint(val_loss, model, path)
            self.counter = 0
    
    def save_checkpoint(self, val_loss, model, path):
        '''保存模型当验证损失减少时'''
        if self.verbose:
            print(f'Validation loss decreased ({self.best_loss:.6f} --> {val_loss:.6f}).')

In [28]:
selected_indices = np.load(f'DIVIDED_DATA/GOwith_0%.npy')
    
    # 根据selected_indices和remaining_indices调整特征
masked_features = features
masked_features[torch.tensor(selected_indices)] = 0
masked_features

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [29]:
device = torch.device('cuda:1')
data = data.to(device)
results = []
num_epochs = 1000
# 加载数据
features = data.x
labels = data.y # 根据你的数据加载函数进行调整
num_iterations = 100
original_features = features.clone()
# 总共需要迭代的次数，这里以逐步增加5%为例，直到100%
model = GCN(num_features=data.x.shape[1], hidden_dim=64, num_classes=3, num_layers=3, activation=F.relu, dropout=0.5)
model.to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.005, weight_decay=0.001)
loss_fn = torch.nn.CrossEntropyLoss()
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.2, patience=50, verbose=True)
for i in range(num_iterations):
    # 加载这次迭代的selected_indices和remaining_indices
    selected_indices = np.load(f'DIVIDED_DATA/GOwith_{i}%.npy')
    
    # 根据selected_indices和remaining_indices调整特征
    masked_features = features.clone()
    masked_features[torch.tensor(selected_indices)] = 0  # 假设features是一个PyTorch tensor
    
    early_stopping = EarlyStopping(patience=200, verbose=True, delta=0.00001)
    
    if i > 0:
        # 从上一个迭代保存的模型中加载参数
        model.load_state_dict(torch.load(f'G-G_DATA/G-G_model_WITH{i-1}.pth'))
        # 重新初始化优化器和调度器
        optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=5e-4)
        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.2, patience=100, verbose=True)
    
    # 模型训练和评估逻辑
    for epoch in range(num_epochs):
        train_loss = train_model_scheduler(model, masked_features, data.y, data.edge_index, optimizer, loss_fn, scheduler, train_mask)
        test_f1, test_auc = evaluate_model(model, masked_features, data.y, data.edge_index, test_mask)
        #high_f1, high_auc = evaluate_model(model, data.x, data.y, data.edge_index, test_high)
        #low_f1, low_auc = evaluate_model(model, data.x, data.y, data.edge_index, test_low)
        if epoch % 50 == 0:  # 每10个epoch打印一次信息
            print(f'Epoch {epoch}: Train Loss: {train_loss:.4f}, Macro_F1: {test_f1:.4f}, AUC_score: {test_auc:.4f}')
        early_stopping(train_loss, model, i)
        if early_stopping.early_stop or epoch == num_epochs - 1:
            results.append({
                            'Train Loss': train_loss,
                            'F1': test_f1,
                            'AUC_score': test_auc
                        })
                            #'highinfo F1': high_f1,                                                            
                            #'highinfo AUC_score': high_auc,
                            #'lowinfo F1': low_f1,
                            #'lowinfo AUC_score': low_auc
            print("acc save")
            rate = 1 - count * (i + 1)
            rate = rate * 100
            print(f'{rate}% node features transform to 0: F1: {test_f1:.4f}, AUC_score: {test_auc:.4f}')
            torch.save(model.state_dict(), f'G-G_DATA/G-G_model_WITH{i}.pth')
            break

Epoch 0: Train Loss: 1.1129, Macro_F1: 0.1140, AUC_score: 0.5000
Validation loss decreased (1.112925 --> 1.112925).
Validation loss decreased (1.111366 --> 1.111366).
Validation loss decreased (1.109829 --> 1.109829).
Validation loss decreased (1.108318 --> 1.108318).
Validation loss decreased (1.106830 --> 1.106830).
Validation loss decreased (1.105366 --> 1.105366).
Validation loss decreased (1.103927 --> 1.103927).
Validation loss decreased (1.102512 --> 1.102512).
Validation loss decreased (1.101122 --> 1.101122).
Validation loss decreased (1.099758 --> 1.099758).
Validation loss decreased (1.098420 --> 1.098420).
Validation loss decreased (1.097107 --> 1.097107).
Validation loss decreased (1.095820 --> 1.095820).
Validation loss decreased (1.094558 --> 1.094558).
Validation loss decreased (1.093320 --> 1.093320).
Validation loss decreased (1.092113 --> 1.092113).
Validation loss decreased (1.090926 --> 1.090926).
Validation loss decreased (1.089764 --> 1.089764).
Validation loss d

In [30]:
results

[{'Train Loss': 1.0517518520355225,
  'F1': array(0.1908291, dtype=float32),
  'AUC_score': 0.5},
 {'Train Loss': 0.6586019396781921,
  'F1': array(0.72071403, dtype=float32),
  'AUC_score': 0.8563770847548539},
 {'Train Loss': 0.4226788282394409,
  'F1': array(0.8346391, dtype=float32),
  'AUC_score': 0.9374641057184944},
 {'Train Loss': 0.3980135917663574,
  'F1': array(0.85567683, dtype=float32),
  'AUC_score': 0.9451525963275172},
 {'Train Loss': 0.3451567590236664,
  'F1': array(0.85655564, dtype=float32),
  'AUC_score': 0.950747870202958},
 {'Train Loss': 0.33657386898994446,
  'F1': array(0.85765743, dtype=float32),
  'AUC_score': 0.952752063199776},
 {'Train Loss': 0.3947474956512451,
  'F1': array(0.8565218, dtype=float32),
  'AUC_score': 0.9525994644041996},
 {'Train Loss': 0.29908865690231323,
  'F1': array(0.8575504, dtype=float32),
  'AUC_score': 0.9565432867831846},
 {'Train Loss': 0.30417898297309875,
  'F1': array(0.8570633, dtype=float32),
  'AUC_score': 0.957423050687

In [31]:
import json
import numpy as np
from numpy import array, float32
class NumpyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        if isinstance(obj, np.generic):
            return obj.item()
        return super(NumpyEncoder, self).default(obj)


# 保存为 JSON 文件
with open('GNN/zeroed_GO_localization.json', 'w') as f:
    json.dump(results, f, cls=NumpyEncoder, indent=4)